version: "2.1"
 
services:

  duplicity:
    image: duplicity:$VERSION_DUPLICITY
    #build: "https://git.scimetis.net/yohan/docker-duplicity.git"
    container_name: duplicity
    entrypoint: /root/entrypoint.sh $SCRIPT
    #restart: unless-stopped
    environment:
      OS_AUTH_URL: $OS_AUTH_URL
      OS_IDENTITY_API_VERSION: $OS_IDENTITY_API_VERSION
      OS_USER_DOMAIN_NAME: $OS_USER_DOMAIN_NAME
      OS_PROJECT_DOMAIN_NAME: $OS_PROJECT_DOMAIN_NAME
      OS_TENANT_ID: $OS_TENANT_ID
      OS_TENANT_NAME: $OS_TENANT_NAME
      OS_USERNAME: $OS_USERNAME
      OS_PASSWORD: $OS_PASSWORD
      OS_REGION_NAME: $OS_REGION_NAME      
    volumes:
      - /mnt/volumes/tmp_duplicity_workdir/data:/mnt/tmp_duplicity_workdir:Z
      - /mnt/volumes/duplicity_cache/data:/mnt/duplicity_cache:Z
      - /mnt/cloud:/mnt/cloud:Z
      - ./backup_scripts:/mnt/scripts:z
      - ./entrypoint.sh:/root/entrypoint.sh:z
      - ./sendmail.py:/root/sendmail.py:z
      - ./mail_credentials.json:/root/mail_credentials.json:z
    network_mode: "host"
