version: "2.1"
 
services:

  duplicity:
    image: duplicity:$VERSION_DUPLICITY
    #build: "https://git.scimetis.net/yohan/docker-duplicity.git"
    container_name: duplicity
    entrypoint: /root/entrypoint.sh $SCRIPT
    #restart: unless-stopped
    environment:
      OS_AUTH_URL: $OS_AUTH_URL
      OS_IDENTITY_API_VERSION: $OS_IDENTITY_API_VERSION
      OS_USER_DOMAIN_NAME: $OS_USER_DOMAIN_NAME
      OS_PROJECT_DOMAIN_NAME: $OS_PROJECT_DOMAIN_NAME
      OS_TENANT_ID: $OS_TENANT_ID
      OS_TENANT_NAME: $OS_TENANT_NAME
      OS_USERNAME: $OS_USERNAME
      OS_PASSWORD: $OS_PASSWORD
      OS_REGION_NAME: $OS_REGION_NAME      
      KEY: $KEY
      DOC_KEY: $DOC_KEY
      SECRETS_ARCHIVE_PASSPHRASE: $SECRETS_ARCHIVE_PASSPHRASE
      DUPLICITY_PASSPHRASE: $DUPLICITY_PASSPHRASE
    volumes:
      - /mnt/volumes:/mnt/volumes:z
      - /mnt/cloud:/mnt/cloud:z
      - ./backup_scripts:/mnt/scripts:z
      - ./entrypoint.sh:/root/entrypoint.sh:z
      - ./sendmail.py:/root/sendmail.py:z
      - ./mail_credentials.json:/root/mail_credentials.json:z
      - ./id_rsa:/root/.ssh/id_rsa:Z
      - ./id_rsa.pub:/root/.ssh/id_rsa.pub:Z
      - ./config:/root/.ssh/config:Z
    network_mode: "host"
